spring:
  application:
    name: oztech-miscroservice-app
  cloud:
    config:
      server:
        git:
          uri: https://github.com/celsolagguijr/SpringCloudServerConfiguration.git
          skip-ssl-validation: false
          searchPaths: config
          clone-on-start: true
    native:
      searchLocations: classpath:offline-repository
---
server:
  port: 8001